[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "murky=lib/murky",
    'foundry-devops/=lib/foundry-devops',
]

[lint]
exclude_lints = ["asm-keccak256", "mixed-case-variable", "screaming-snake-case-immutable", "unsafe-cheatcode"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
